FROM python:3.9-slim
WORKDIR /app
COPY backend/requirements.txt /app/
RUN pip install -r requirements.txt
COPY backend/ /app/
CMD ["gunicorn", "nutriconnect_backend.wsgi:application", "--bind", "0.0.0.0:8000"]
