# Generated by Django 5.1.4 on 2024-12-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile_bmi_profile_meal_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekly_nutrition_plan',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekly_workout_plan',
            field=models.JSONField(default=dict),
        ),
    ]
